---
- name: Inicio de ejecuci贸n
  debug:
    msg: Playbook para pruebas de ejecuci贸n remota

- name: Definiendo las variables
  set_fact:
    name: User

- name: Ejecuci贸n de manera remota
  shell: | 
    echo "Usuario: {name}!"

- name: Transferencia del script
  copy:
    src: "{{ playbook_dir }}/hello-rol/files/main.sh"
    dest: /tmp/main.sh

- name: Ejecuci贸n remota del script
  shell: | 
    /bin/bash /tmp/main.sh
